### ISSUE TITLE
Missing top part of navigation

### ISSUE THREAD

**Issue by rachelfwells** [rachelfwells/eHound#1]
@ acporter fyi 

Hi Sam,

Thanks for smashing this out. I will log a few amends here. Thanks again
## 

Currently the top of the navigation is missing and needs a little more even white space above and below logo

![screen shot 2015-09-02 at 5 05 14 pm](https://cloud.githubusercontent.com/assets/5561629/9625239/ea8890ea-5197-11e5-89b7-34338c271554.png)

Needs to look like this and should be a default setting in the template as the psd's were supplied with it in there. Need contact details top left and myHound login top right. Another brown bar and white text. 

![1-ehound-homepage-v1-slider-testimonial](https://cloud.githubusercontent.com/assets/5561629/9625090/67fdf9d6-5196-11e5-8164-771b5ea209ce.jpg)

**Comment by rachelfwells** [comment]
@acporter  @ashleyporter fyi

**Comment by samadd** [comment]
Added top bar and set to brown colour.
