### ISSUE TITLE
Wide Bay = Auswide

### ISSUE THREAD

**Issue by rachelfwells** [rachelfwells/eHound#12]
On the existing site there is Wide Bay but they have changed names to Auswide.

@acporter do you want to simply update this with their new name for now, rewrite or remove?

@samadd fyi

**Comment by ashleyporter** [comment]
Hi @rachelfwells 

Just update name for now.

Cheers

**Comment by rachelfwells** [comment]
Hi @samadd Ont he case studies pages please use existing content for Wide Bay but change all references to that name to Auswide. Thanks

**Comment by samadd** [comment]
Taken the content and changed Wide Bay to Auswide.
