### ISSUE TITLE
Call Centre Locator Image

### ISSUE THREAD

**Issue by rachelfwells** [rachelfwells/eHound#13]
Have resized this image - can you please try it here - http://dev.ehoundplatform.com/call-centre-locator

THANKS :)

**Comment by rachelfwells** [comment]
![callcentre-01-1](https://cloud.githubusercontent.com/assets/5561629/9629941/ff2f832e-51b9-11e5-87db-5db8aa3b8f48.jpg)

**Comment by samadd** [comment]
Replaced with this copy.
