### ISSUE TITLE
Slider 

### ISSUE THREAD

**Issue by rachelfwells** [rachelfwells/eHound#2]
• We may need to change this image @ashleyporter @acporter - Any luck with Westpac?

• Can the two boxes 'Read More' and 'Get in touch' be a little closer together? Look a little too far apart. They would be great at about 40 to 45 pixels apart.

• When this slider resizes these two boxes are not centrally aligned - see screengrab. Need to go a little to the left

**Comment by samadd** [comment]
Gap reduced - centre alignment fixed however this results in overlap between buttons on narrow screen. I'll get a workaround worked out...

**Comment by samadd** [comment]
The buttons are anchored from the center now - to avoid the overlap completely on minimum width in Chrome the gap has to be a bit too wide on a 'normal' view. As of now there is a slight overlap when on a narrow view, but the buttons are close enough together on a wider view.

Have a look and see if you think the balance is okay.

**Comment by rachelfwells** [comment]
looks fine. Thanks Sam :)
