### ISSUE TITLE
Missing first letter in blurb - 

### ISSUE THREAD

**Issue by rachelfwells** [rachelfwells/eHound#4]
http://dev.ehoundplatform.com/web-apps-locator 

![screen shot 2015-09-02 at 5 38 32 pm](https://cloud.githubusercontent.com/assets/5561629/9625443/7cb158e8-5199-11e5-9c39-b808a7041ba4.png)

http://dev.ehoundplatform.com/call-centre-locator
![screen shot 2015-09-02 at 5 39 26 pm](https://cloud.githubusercontent.com/assets/5561629/9625451/9680691c-5199-11e5-894e-7119f60aca47.png)

http://dev.ehoundplatform.com/analytics
![screen shot 2015-09-02 at 5 39 55 pm](https://cloud.githubusercontent.com/assets/5561629/9625461/a7d4b308-5199-11e5-9d30-475dce81d2e4.png)

**Comment by samadd** [comment]
Done!
