### ISSUE TITLE
Sub heads too big on these pages

### ISSUE THREAD

**Issue by rachelfwells** [rachelfwells/eHound#5]
http://dev.ehoundplatform.com/call-centre-locator

and

http://dev.ehoundplatform.com/analytics

![screen shot 2015-09-02 at 5 41 03 pm](https://cloud.githubusercontent.com/assets/5561629/9625483/d48c4e42-5199-11e5-9985-f0cfa76082dc.png)

please make them the same size as http://dev.ehoundplatform.com/web-apps-locator

**Comment by samadd** [comment]
Adjusted style sheet to match sizes between h3 in 3 columns and 4 columns.

**Comment by ashleyporter** [comment]
Thanks @samadd 

I will review today and we should be good to go over the next 24-48 hours.

Cheers

**Comment by ashleyporter** [comment]
@samadd 

Also, it should read:

eHound has more than ten years experience...

Cheers

**Comment by ashleyporter** [comment]
Also, text change for call centre locator:

Leveraging the latest advances in IP-telephony, the eHound Call Centre Store Locator allows you to connect customers to their nearest store, branch or stockist quickly and easily.

**Comment by samadd** [comment]
Changed.
