### ISSUE TITLE
First line on http://dev.ehoundplatform.com/call-centre-locator

### ISSUE THREAD

**Issue by rachelfwells** [rachelfwells/eHound#6]
Too small. Please make this first line like this:

![screen shot 2015-09-02 at 5 42 47 pm](https://cloud.githubusercontent.com/assets/5561629/9625513/1df2b788-519a-11e5-9536-6be739e069d7.png)

like this:
![screen shot 2015-09-02 at 5 49 00 pm](https://cloud.githubusercontent.com/assets/5561629/9625639/0833529e-519b-11e5-8a67-0e2c94f284ff.png)

**Comment by samadd** [comment]
Changed top line to h3
