### ISSUE TITLE
Font change to brown not black - lower priority

### ISSUE THREAD

**Issue by rachelfwells** [rachelfwells/eHound#7]
I had this as brown in the jpgs but it may just be easier to make it grey like the Call Centre and Analytics pages

![screen shot 2015-09-02 at 5 44 05 pm](https://cloud.githubusercontent.com/assets/5561629/9625541/460b8c36-519a-11e5-95b3-ea903499d67b.png)

**Comment by samadd** [comment]
Changed to brown.
