### ISSUE TITLE
Case studies

### ISSUE THREAD

**Issue by rachelfwells** [rachelfwells/eHound#8]
Please advise the size of the box and i will do this - can i upload from back end myself?

Thanks

**Comment by rachelfwells** [comment]
I think this size is correct - please use these for now. Thanks

![westpac](https://cloud.githubusercontent.com/assets/5561629/9629547/cd994c26-51b6-11e5-89cb-48236f1e9783.jpg)
![jax](https://cloud.githubusercontent.com/assets/5561629/9629548/cd9d9010-51b6-11e5-8759-2a297ee7fd61.jpg)
![qpcu](https://cloud.githubusercontent.com/assets/5561629/9629549/cda08be4-51b6-11e5-94f3-7ac54e803bc6.jpg)
![auswide](https://cloud.githubusercontent.com/assets/5561629/9629550/cdb3eb9e-51b6-11e5-9ff4-fce3cecf8622.jpg)
![lmg](https://cloud.githubusercontent.com/assets/5561629/9629551/cdb5d3dc-51b6-11e5-959a-d9d6da6c67c1.jpg)
![heritage](https://cloud.githubusercontent.com/assets/5561629/9629552/cdd91e64-51b6-11e5-81a3-417a4efa75a7.jpg)

**Comment by samadd** [comment]
Size fine - images all in a row!
